#ifndef SREPAIRMODEL_H
#define SREPAIRMODEL_H

#include "scomrecord.h"
#include <QObject>
#include <QString>
#include <QDate>
#include "sdevmdlmodel.h"
#include "sclientmodel.h"
#include "saletablemodel.h"

class SRepairModel : public SComRecord
{
    Q_OBJECT
public:
    explicit SRepairModel(QObject *parent = nullptr);
    explicit SRepairModel(const int, QObject *parent = nullptr);
    ~SRepairModel();
    void load(const int);
    bool isHidden();
    void setHidden(const bool);
    QString title();
    void setTitle(const QString);
    int clientId();
    void setClientId(const int);
    int classId();
    void setClassId(const int);
    int vendorId();
    void setVendorId(const int);
    int deviceId();
    void setDeviceId(const int);
    QString serialNumber();
    void setSerialNumber(const QString);
    int companyIndex();
    void setCompanyIndex(const int);
    int officeIndex();
    void setOfficeIndex(const int);
    int startOfficeIndex();
    void setStartOfficeIndex(const int);
    int managerIndex();
    void setManagerIndex(const int);
    int currentManagerIndex();
    void setCurrentManagerIndex(const int);
    int masterIndex();
    void setMasterIndex(const int);
    QString diagnosticResult();
    void setDiagnosticResult(const QString);
    QDate inDate();
    void setInDate(const QDate);
    QDate outDate();
    void setOutDate(const QDate);
    int stateIndex();
    void setStateIndex(const int);
    int newStateIndex();
    void setNewStateIndex(const int);
    int userLock();
    void setUserLock(const int);
    QDate lockDatetime();
    void setLockDatetime(const QDate);
    bool expressRepair();
    void setExpressRepair(const bool);
    bool quickRepair();
    void setQuickRepair(const bool);
    bool isWarranty();
    void setIsWarranty(const bool);
    bool isRepeat();
    void setIsRepeat(const bool);
    int paymentSystemIndex();
    void setPaymentSystemIndex(const int);
    bool isCardPayment();
    void setIsCardPayment(const bool);
    bool canFormat();
    void setCanFormat(const bool);
    bool printCheck();
    void setPrintCheck(const bool);
    int boxIndex();
    void setBoxIndex(const int);
    QString warrantyLabel();
    void setWarrantyLabel(const QString);
    QString extNotes();
    void setExtNotes(const QString);
    bool isPrepaid();
    void setIsPrepaid(const bool);
    int prepaidType();
    void setPrepaidType(const int);
    float prepaidSumm();
    void setPrepaidSumm(const float);
    int prepaidOrder();
    void setPrepaidOrder(const int);
    bool isPreAgreed();
    void setIsPreAgreed(const bool);
    bool isDebt();
    void setIsDebt(const bool);
    float preAgreedAmount();
    void setPreAgreedAmount(const float);
    float repairCost();
    void setRepairCost(const float);
    float realRepairCost();
    void setRealRepairCost(const float);
    float partsCost();
    void setPartsCost(const float);
    QString fault();
    void setFault(const QString);
    QString complect();
    void setComplect(const QString);
    QString look();
    void setLook(const QString);
    bool thirsPartySc();
    void setThirsPartySc(const bool);
    QDate lastSave();
    void setLastSave(const QDate);
    QDate lastStatusChanged();
    void setLastStatusChanged(const QDate);
    int warrantyDays();
    void setWarrantyDays(const int);
    QString barcode();
    void setBarcode(const QString);
    QString rejectReason();
    void setRejectReason(const QString);
    int informedStatusIndex();
    void setInformedStatusIndex(const int);
    QString imageIds();
    void setImageIds(const QString);
    QColor color();
    void setColor(const QColor);
    QString orderMoving();
    void setOrderMoving(const QString);
    int early();
    void setEarly(const int);
    QString extEarly();
    void setExtEarly(const QString);
    QString issuedMsg();
    void setIssuedMsg(const QString);
    bool smsInform();
    void setSmsInform(const bool);
    int invoice();
    void setInvoice(const int);
    int cartridge();
    void setCartridge(const int);
    bool termsControl();
    void setTermsControl(const bool);

private:
    SClientModel *clientModel;
    bool m_isHidden;
    QString m_title;
    int m_clientId;
    int m_typeIndex;
    int m_makerIndex;
    int m_modelIndex;
    QString m_serialNumber;
    int m_companyIndex;
    int m_officeIndex;
    int m_startOfficeIndex;
    int m_managerIndex;
    int m_currentManagerIndex;
    int m_masterIndex;
    QString m_diagnosticResult;
    QDate m_inDate;
    QDate m_outDate;
    int m_stateIndex;
    int m_newStateIndex;
    int m_userLock;
    QDate m_lockDatetime;
    bool m_expressRepair;
    bool m_quickRepair;
    bool m_isWarranty;
    bool m_isRepeat;
    int m_paymentSystemIndex;
    bool m_isCardPayment;
    bool m_canFormat;
    bool m_printCheck;
    int m_boxIndex;
    QString m_warrantyLabel;
    QString m_extNotes;
    bool m_isPrepaid;
    int m_prepaidType;
    int m_prepaidSumm;
    int m_prepaidOrder;
    bool m_isPreAgreed;
    bool m_isDebt;
    int m_preAgreedAmount;
    int m_repairCost;
    int m_realRepairCost;
    int m_partsCost;
    QString m_fault;
    QString m_complect;
    QString m_look;
    bool m_thirsPartySc;
    QDate m_lastSave;
    QDate m_lastStatusChanged;
    int m_warrantyDays;
    QString m_barcode;
    QString m_rejectReason;
    int m_informedStatusIndex;
    QString m_imageIds;
    QColor m_color;
    QString m_orderMoving;
    int m_early;
    QString m_extEarly;
    QString m_issuedMsg;
    bool m_smsInform;
    int m_invoice;
    int m_cartridge;
    int m_vendorId;
    bool m_termsControl;
};

#endif // SREPAIRMODEL_H
